### ISSUE TITLE
小数点以下四捨五入モードにおいて5が切り捨てられている？

### ISSUE THREAD

**Issue by sudame** [forkexecsatoshi/git_training_new#4]
## 操作手順
* 1.25 * 2 をしたら
* 2が答えになる

## 本来の想定
* 1.25 * 2 をしたら
* 2.5 が真値なので四捨五入をして3になるべき

## 操作環境
* **OS** Windows 10
* **OSバージョン** 19043.1055
* **ブラウザ** Firefox
* **ブラウザバージョン**  90.0b7

**Comment by yoshioka-takuma** [comment]
修正されました
